name = "hardlyardi/light"
version = "0.1.0"
description = "A remote event wrapper for Roblox"
authors = ["hardlyardi"]
repository = "https://github.com/hardlyardi/light"
license = "MIT"
private = false

workspace_members = ["pkgs/*"]

[engines]
pesde = "0.7.0-rc.3"
lune = "^0.9.3"

[target]
environment = "roblox"

[indices]
default = "https://github.com/pesde-pkg/index"

[dev_dependencies]
rojo_scripts = { name = "pesde/scripts_rojo", version = "^0.1.0", target = "lune" }
rojo = { name = "pesde/rojo", version = "^7.4.4", target = "lune" }
