--!nocheck
export type InstanceClassname =
	"Instance"
	| "AccessoryDescription"
	| "Accoutrement"
	| "Accessory"
	| "Hat"
	| "ActivityHistoryEventService"
	| "AdPortal"
	| "AdService"
	| "AdvancedDragger"
	| "Animation"
	| "AnimationClip"
	| "CurveAnimation"
	| "KeyframeSequence"
	| "AnimationController"
	| "AnimationFromVideoCreatorService"
	| "AnimationRigData"
	| "AnimationTrack"
	| "Animator"
	| "Annotation"
	| "WorkspaceAnnotation"
	| "AnnotationsService"
	| "AssetService"
	| "Atmosphere"
	| "Attachment"
	| "Bone"
	| "AudioAnalyzer"
	| "AudioChannelMixer"
	| "AudioChannelSplitter"
	| "AudioChorus"
	| "AudioCompressor"
	| "AudioDeviceInput"
	| "AudioDeviceOutput"
	| "AudioDistortion"
	| "AudioEcho"
	| "AudioEmitter"
	| "AudioEqualizer"
	| "AudioFader"
	| "AudioFilter"
	| "AudioFlanger"
	| "AudioLimiter"
	| "AudioListener"
	| "AudioPitchShifter"
	| "AudioPlayer"
	| "AudioReverb"
	| "AudioTextToSpeech"
	| "AuroraScriptService"
	| "AuroraService"
	| "AvatarChatService"
	| "AvatarCreationService"
	| "Backpack"
	| "BadgeService"
	| "BasePlayerGui"
	| "PlayerGui"
	| "StarterGui"
	| "BaseRemoteEvent"
	| "RemoteEvent"
	| "UnreliableRemoteEvent"
	| "BaseWrap"
	| "WrapDeformer"
	| "WrapLayer"
	| "WrapTarget"
	| "Beam"
	| "BindableEvent"
	| "BindableFunction"
	| "BodyMover"
	| "BodyAngularVelocity"
	| "BodyForce"
	| "BodyGyro"
	| "BodyPosition"
	| "BodyThrust"
	| "BodyVelocity"
	| "RocketPropulsion"
	| "BodyPartDescription"
	| "CaptureService"
	| "ChangeHistoryService"
	| "CharacterAppearance"
	| "BodyColors"
	| "CharacterMesh"
	| "Clothing"
	| "Pants"
	| "Shirt"
	| "ShirtGraphic"
	| "Skin"
	| "ClickDetector"
	| "DragDetector"
	| "Clouds"
	| "Collaborator"
	| "CollaboratorsService"
	| "CollectionService"
	| "CommerceService"
	| "Configuration"
	| "ConfigureServerService"
	| "Constraint"
	| "AlignOrientation"
	| "AlignPosition"
	| "AngularVelocity"
	| "AnimationConstraint"
	| "BallSocketConstraint"
	| "HingeConstraint"
	| "LineForce"
	| "LinearVelocity"
	| "PlaneConstraint"
	| "Plane"
	| "RigidConstraint"
	| "RodConstraint"
	| "RopeConstraint"
	| "SlidingBallConstraint"
	| "CylindricalConstraint"
	| "PrismaticConstraint"
	| "SpringConstraint"
	| "Torque"
	| "TorsionSpringConstraint"
	| "UniversalConstraint"
	| "VectorForce"
	| "ContextActionService"
	| "Controller"
	| "HumanoidController"
	| "SkateboardController"
	| "VehicleController"
	| "ControllerBase"
	| "AirController"
	| "ClimbController"
	| "GroundController"
	| "SwimController"
	| "ControllerManager"
	| "CookiesService"
	| "CoreScriptDebuggingManagerHelper"
	| "CreatorStoreService"
	| "CustomEvent"
	| "CustomEventReceiver"
	| "DataModelMesh"
	| "BevelMesh"
	| "BlockMesh"
	| "CylinderMesh"
	| "FileMesh"
	| "SpecialMesh"
	| "DataModelSession"
	| "Debris"
	| "DebuggerBreakpoint"
	| "DebuggerWatch"
	| "Dialog"
	| "DialogChoice"
	| "Dragger"
	| "EditableService"
	| "EulerRotationCurve"
	| "EventIngestService"
	| "ExperienceAuthService"
	| "Explosion"
	| "FaceControls"
	| "FaceInstance"
	| "Decal"
	| "Texture"
	| "FacialAnimationStreamingServiceV2"
	| "Feature"
	| "Hole"
	| "MotorFeature"
	| "FeatureRestrictionManager"
	| "Fire"
	| "FlagStandService"
	| "FloatCurve"
	| "FlyweightService"
	| "CSGDictionaryService"
	| "NonReplicatedCSGDictionaryService"
	| "Folder"
	| "ForceField"
	| "FriendService"
	| "FunctionalTest"
	| "GamePassService"
	| "GenerationService"
	| "GenericChallengeService"
	| "Geometry"
	| "GeometryService"
	| "GoogleAnalyticsConfiguration"
	| "GuiBase"
	| "GuiBase2d"
	| "GuiObject"
	| "CanvasGroup"
	| "Frame"
	| "GuiButton"
	| "ImageButton"
	| "TextButton"
	| "GuiLabel"
	| "ImageLabel"
	| "TextLabel"
	| "ScrollingFrame"
	| "TextBox"
	| "VideoDisplay"
	| "VideoFrame"
	| "ViewportFrame"
	| "LayerCollector"
	| "BillboardGui"
	| "ScreenGui"
	| "GuiMain"
	| "SurfaceGuiBase"
	| "AdGui"
	| "SurfaceGui"
	| "GuiBase3d"
	| "FloorWire"
	| "InstanceAdornment"
	| "SelectionBox"
	| "PVAdornment"
	| "HandleAdornment"
	| "BoxHandleAdornment"
	| "ConeHandleAdornment"
	| "CylinderHandleAdornment"
	| "ImageHandleAdornment"
	| "LineHandleAdornment"
	| "SphereHandleAdornment"
	| "ParabolaAdornment"
	| "SelectionSphere"
	| "PartAdornment"
	| "HandlesBase"
	| "ArcHandles"
	| "Handles"
	| "SurfaceSelection"
	| "SelectionLasso"
	| "SelectionPartLasso"
	| "SelectionPointLasso"
	| "Path2D"
	| "GuidRegistryService"
	| "HapticEffect"
	| "HeapProfilerService"
	| "HeatmapService"
	| "HiddenSurfaceRemovalAsset"
	| "Highlight"
	| "Hopper"
	| "HttpRbxApiService"
	| "HttpRequest"
	| "HttpService"
	| "Humanoid"
	| "HumanoidDescription"
	| "HumanoidRigDescription"
	| "IKControl"
	| "ILegacyStudioBridge"
	| "InputAction"
	| "InputBinding"
	| "InputContext"
	| "InputObject"
	| "InsertService"
	| "JointInstance"
	| "DynamicRotate"
	| "RotateP"
	| "RotateV"
	| "Glue"
	| "ManualSurfaceJointInstance"
	| "ManualGlue"
	| "ManualWeld"
	| "Motor"
	| "Motor6D"
	| "Rotate"
	| "Snap"
	| "VelocityMotor"
	| "Weld"
	| "JointsService"
	| "KeyboardService"
	| "Keyframe"
	| "KeyframeMarker"
	| "Light"
	| "PointLight"
	| "SpotLight"
	| "SurfaceLight"
	| "Lighting"
	| "LiveScriptingService"
	| "LocalizationTable"
	| "LodDataEntity"
	| "LogService"
	| "LoginService"
	| "LuaSourceContainer"
	| "AuroraScript"
	| "BaseScript"
	| "Script"
	| "LocalScript"
	| "ModuleScript"
	| "LuaWebService"
	| "MLModelDeliveryService"
	| "MarkerCurve"
	| "MarketplaceService"
	| "MaterialService"
	| "MaterialVariant"
	| "MemoryStoreService"
	| "Message"
	| "Hint"
	| "Mouse"
	| "PlayerMouse"
	| "PluginMouse"
	| "NetworkMarker"
	| "NetworkPeer"
	| "NoCollisionConstraint"
	| "NotificationService"
	| "OperationGraph"
	| "PVInstance"
	| "BasePart"
	| "CornerWedgePart"
	| "FormFactorPart"
	| "Part"
	| "FlagStand"
	| "Platform"
	| "Seat"
	| "SpawnLocation"
	| "WedgePart"
	| "Terrain"
	| "TriangleMeshPart"
	| "MeshPart"
	| "PartOperation"
	| "IntersectOperation"
	| "NegateOperation"
	| "UnionOperation"
	| "TrussPart"
	| "VehicleSeat"
	| "Model"
	| "Actor"
	| "BackpackItem"
	| "HopperBin"
	| "Tool"
	| "Flag"
	| "Status"
	| "WorldRoot"
	| "Workspace"
	| "WorldModel"
	| "PackageLink"
	| "PartOperationAsset"
	| "ParticleEmitter"
	| "PathfindingLink"
	| "PathfindingModifier"
	| "PermissionsService"
	| "PhysicsService"
	| "Player"
	| "PlayerHydrationService"
	| "Players"
	| "Plugin"
	| "PluginCapabilities"
	| "PluginManager"
	| "PluginToolbar"
	| "PluginToolbarButton"
	| "PointsService"
	| "PoseBase"
	| "NumberPose"
	| "Pose"
	| "PostEffect"
	| "BloomEffect"
	| "BlurEffect"
	| "ColorCorrectionEffect"
	| "ColorGradingEffect"
	| "DepthOfFieldEffect"
	| "SunRaysEffect"
	| "ProcessInstancePhysicsService"
	| "ProximityPrompt"
	| "ProximityPromptService"
	| "RbxAnalyticsService"
	| "ReflectionMetadata"
	| "ReflectionMetadataCallbacks"
	| "ReflectionMetadataClasses"
	| "ReflectionMetadataEnums"
	| "ReflectionMetadataEvents"
	| "ReflectionMetadataFunctions"
	| "ReflectionMetadataItem"
	| "ReflectionMetadataClass"
	| "ReflectionMetadataEnum"
	| "ReflectionMetadataEnumItem"
	| "ReflectionMetadataMember"
	| "ReflectionMetadataProperties"
	| "ReflectionMetadataYieldFunctions"
	| "RemoteCursorService"
	| "RemoteFunction"
	| "RenderingTest"
	| "ReplicatedFirst"
	| "ReplicatedStorage"
	| "RobloxReplicatedStorage"
	| "RomarkRbxAnalyticsService"
	| "RomarkService"
	| "RotationCurve"
	| "SafetyService"
	| "ScriptDebugger"
	| "ScriptProfilerService"
	| "ScriptService"
	| "Selection"
	| "SelectionHighlightManager"
	| "SensorBase"
	| "AtmosphereSensor"
	| "BuoyancySensor"
	| "ControllerSensor"
	| "ControllerPartSensor"
	| "FluidForceSensor"
	| "SerializationService"
	| "ServiceProvider"
	| "DataModel"
	| "GenericSettings"
	| "AnalysticsSettings"
	| "GlobalSettings"
	| "UserSettings"
	| "ServiceVisibilityService"
	| "SessionService"
	| "Sky"
	| "Smoke"
	| "Sound"
	| "SoundEffect"
	| "ChorusSoundEffect"
	| "CompressorSoundEffect"
	| "CustomSoundEffect"
	| "AssetSoundEffect"
	| "ChannelSelectorSoundEffect"
	| "DistortionSoundEffect"
	| "EchoSoundEffect"
	| "EqualizerSoundEffect"
	| "FlangeSoundEffect"
	| "PitchShiftSoundEffect"
	| "ReverbSoundEffect"
	| "TremoloSoundEffect"
	| "SoundGroup"
	| "SoundService"
	| "Sparkles"
	| "SpawnerService"
	| "StandalonePluginScripts"
	| "StarterGear"
	| "StarterPack"
	| "StarterPlayer"
	| "StarterPlayerScripts"
	| "StarterCharacterScripts"
	| "Stats"
	| "StatsItem"
	| "RunningAverageItemDouble"
	| "RunningAverageItemInt"
	| "RunningAverageTimeIntervalItem"
	| "TotalCountTimeIntervalItem"
	| "StudioData"
	| "StyleBase"
	| "StyleRule"
	| "StyleSheet"
	| "StyleDerive"
	| "StyleLink"
	| "SurfaceAppearance"
	| "Team"
	| "TeamCreateData"
	| "TeamCreatePublishService"
	| "Teams"
	| "TeleportAsyncResult"
	| "TeleportOptions"
	| "TeleportService"
	| "TerrainDetail"
	| "TerrainRegion"
	| "TestService"
	| "TextBoxService"
	| "TextChannel"
	| "TextChatCommand"
	| "BubbleChatConfiguration"
	| "ChannelTabsConfiguration"
	| "ChatInputBarConfiguration"
	| "ChatWindowConfiguration"
	| "TextChatMessage"
	| "TextChatMessageProperties"
	| "BubbleChatMessageProperties"
	| "ChatWindowMessageProperties"
	| "TextChatService"
	| "TextSource"
	| "TimerService"
	| "TouchInputService"
	| "TouchTransmitter"
	| "Trail"
	| "TweenBase"
	| "Tween"
	| "TweenService"
	| "UGCAvatarService"
	| "UIBase"
	| "UIComponent"
	| "UIConstraint"
	| "UIAspectRatioConstraint"
	| "UISizeConstraint"
	| "UITextSizeConstraint"
	| "UICorner"
	| "UIDragDetector"
	| "UIFlexItem"
	| "UIGradient"
	| "UILayout"
	| "UIGridStyleLayout"
	| "UIGridLayout"
	| "UIListLayout"
	| "UIPageLayout"
	| "UITableLayout"
	| "UIPadding"
	| "UIScale"
	| "UIStroke"
	| "UniqueIdLookupService"
	| "UnvalidatedAssetService"
	| "UserService"
	| "VRService"
	| "VRStatusService"
	| "ValueBase"
	| "BinaryStringValue"
	| "BoolValue"
	| "BrickColorValue"
	| "CFrameValue"
	| "Color3Value"
	| "DoubleConstrainedValue"
	| "IntConstrainedValue"
	| "IntValue"
	| "NumberValue"
	| "ObjectValue"
	| "RayValue"
	| "StringValue"
	| "Vector3Value"
	| "Vector3Curve"
	| "VersionControlService"
	| "VideoCaptureService"
	| "VideoPlayer"
	| "VideoService"
	| "VirtualInputManager"
	| "VisibilityCheckDispatcher"
	| "VisualizationMode"
	| "VisualizationModeCategory"
	| "VisualizationModeService"
	| "VoiceChatInternal"
	| "VoiceChatService"
	| "WeldConstraint"
	| "Wire"
	| "SkateboardPlatform"
	| "WireframeHandleAdornment"

export type InstanceClassnameTable = {
	Instance: Instance,
	AccessoryDescription: AccessoryDescription,
	Accoutrement: Accoutrement,
	Accessory: Accessory,
	Hat: Hat,
	ActivityHistoryEventService: ActivityHistoryEventService,
	AdPortal: AdPortal,
	AdService: AdService,
	AdvancedDragger: AdvancedDragger,
	Animation: Animation,
	AnimationClip: AnimationClip,
	CurveAnimation: CurveAnimation,
	KeyframeSequence: KeyframeSequence,
	AnimationController: AnimationController,
	AnimationFromVideoCreatorService: AnimationFromVideoCreatorService,
	AnimationRigData: AnimationRigData,
	AnimationTrack: AnimationTrack,
	Animator: Animator,
	Annotation: Annotation,
	WorkspaceAnnotation: WorkspaceAnnotation,
	AnnotationsService: AnnotationsService,
	AssetService: AssetService,
	Atmosphere: Atmosphere,
	Attachment: Attachment,
	Bone: Bone,
	AudioAnalyzer: AudioAnalyzer,
	AudioChannelMixer: AudioChannelMixer,
	AudioChannelSplitter: AudioChannelSplitter,
	AudioChorus: AudioChorus,
	AudioCompressor: AudioCompressor,
	AudioDeviceInput: AudioDeviceInput,
	AudioDeviceOutput: AudioDeviceOutput,
	AudioDistortion: AudioDistortion,
	AudioEcho: AudioEcho,
	AudioEmitter: AudioEmitter,
	AudioEqualizer: AudioEqualizer,
	AudioFader: AudioFader,
	AudioFilter: AudioFilter,
	AudioFlanger: AudioFlanger,
	AudioLimiter: AudioLimiter,
	AudioListener: AudioListener,
	AudioPitchShifter: AudioPitchShifter,
	AudioPlayer: AudioPlayer,
	AudioReverb: AudioReverb,
	AudioTextToSpeech: AudioTextToSpeech,
	AuroraScriptService: AuroraScriptService,
	AuroraService: AuroraService,
	AvatarChatService: AvatarChatService,
	AvatarCreationService: AvatarCreationService,
	Backpack: Backpack,
	BadgeService: BadgeService,
	BasePlayerGui: BasePlayerGui,
	PlayerGui: PlayerGui,
	StarterGui: StarterGui,
	BaseRemoteEvent: BaseRemoteEvent,
	RemoteEvent: RemoteEvent,
	UnreliableRemoteEvent: UnreliableRemoteEvent,
	BaseWrap: BaseWrap,
	WrapDeformer: WrapDeformer,
	WrapLayer: WrapLayer,
	WrapTarget: WrapTarget,
	Beam: Beam,
	BindableEvent: BindableEvent,
	BindableFunction: BindableFunction,
	BodyMover: BodyMover,
	BodyAngularVelocity: BodyAngularVelocity,
	BodyForce: BodyForce,
	BodyGyro: BodyGyro,
	BodyPosition: BodyPosition,
	BodyThrust: BodyThrust,
	BodyVelocity: BodyVelocity,
	RocketPropulsion: RocketPropulsion,
	BodyPartDescription: BodyPartDescription,
	CaptureService: CaptureService,
	ChangeHistoryService: ChangeHistoryService,
	CharacterAppearance: CharacterAppearance,
	BodyColors: BodyColors,
	CharacterMesh: CharacterMesh,
	Clothing: Clothing,
	Pants: Pants,
	Shirt: Shirt,
	ShirtGraphic: ShirtGraphic,
	Skin: Skin,
	ClickDetector: ClickDetector,
	DragDetector: DragDetector,
	Clouds: Clouds,
	Collaborator: Collaborator,
	CollaboratorsService: CollaboratorsService,
	CollectionService: CollectionService,
	CommerceService: CommerceService,
	Configuration: Configuration,
	ConfigureServerService: ConfigureServerService,
	Constraint: Constraint,
	AlignOrientation: AlignOrientation,
	AlignPosition: AlignPosition,
	AngularVelocity: AngularVelocity,
	AnimationConstraint: AnimationConstraint,
	BallSocketConstraint: BallSocketConstraint,
	HingeConstraint: HingeConstraint,
	LineForce: LineForce,
	LinearVelocity: LinearVelocity,
	PlaneConstraint: PlaneConstraint,
	Plane: Plane,
	RigidConstraint: RigidConstraint,
	RodConstraint: RodConstraint,
	RopeConstraint: RopeConstraint,
	SlidingBallConstraint: SlidingBallConstraint,
	CylindricalConstraint: CylindricalConstraint,
	PrismaticConstraint: PrismaticConstraint,
	SpringConstraint: SpringConstraint,
	Torque: Torque,
	TorsionSpringConstraint: TorsionSpringConstraint,
	UniversalConstraint: UniversalConstraint,
	VectorForce: VectorForce,
	ContextActionService: ContextActionService,
	Controller: Controller,
	HumanoidController: HumanoidController,
	SkateboardController: SkateboardController,
	VehicleController: VehicleController,
	ControllerBase: ControllerBase,
	AirController: AirController,
	ClimbController: ClimbController,
	GroundController: GroundController,
	SwimController: SwimController,
	ControllerManager: ControllerManager,
	CookiesService: CookiesService,
	CoreScriptDebuggingManagerHelper: CoreScriptDebuggingManagerHelper,
	CreatorStoreService: CreatorStoreService,
	CustomEvent: CustomEvent,
	CustomEventReceiver: CustomEventReceiver,
	DataModelMesh: DataModelMesh,
	BevelMesh: BevelMesh,
	BlockMesh: BlockMesh,
	CylinderMesh: CylinderMesh,
	FileMesh: FileMesh,
	SpecialMesh: SpecialMesh,
	DataModelSession: DataModelSession,
	Debris: Debris,
	DebuggerBreakpoint: DebuggerBreakpoint,
	DebuggerWatch: DebuggerWatch,
	Dialog: Dialog,
	DialogChoice: DialogChoice,
	Dragger: Dragger,
	EditableService: EditableService,
	EulerRotationCurve: EulerRotationCurve,
	EventIngestService: EventIngestService,
	ExperienceAuthService: ExperienceAuthService,
	Explosion: Explosion,
	FaceControls: FaceControls,
	FaceInstance: FaceInstance,
	Decal: Decal,
	Texture: Texture,
	FacialAnimationStreamingServiceV2: FacialAnimationStreamingServiceV2,
	Feature: Feature,
	Hole: Hole,
	MotorFeature: MotorFeature,
	FeatureRestrictionManager: FeatureRestrictionManager,
	Fire: Fire,
	FlagStandService: FlagStandService,
	FloatCurve: FloatCurve,
	FlyweightService: FlyweightService,
	CSGDictionaryService: CSGDictionaryService,
	NonReplicatedCSGDictionaryService: NonReplicatedCSGDictionaryService,
	Folder: Folder,
	ForceField: ForceField,
	FriendService: FriendService,
	FunctionalTest: FunctionalTest,
	GamePassService: GamePassService,
	GenerationService: GenerationService,
	GenericChallengeService: GenericChallengeService,
	Geometry: Geometry,
	GeometryService: GeometryService,
	GoogleAnalyticsConfiguration: GoogleAnalyticsConfiguration,
	GuiBase: GuiBase,
	GuiBase2d: GuiBase2d,
	GuiObject: GuiObject,
	CanvasGroup: CanvasGroup,
	Frame: Frame,
	GuiButton: GuiButton,
	ImageButton: ImageButton,
	TextButton: TextButton,
	GuiLabel: GuiLabel,
	ImageLabel: ImageLabel,
	TextLabel: TextLabel,
	ScrollingFrame: ScrollingFrame,
	TextBox: TextBox,
	VideoDisplay: VideoDisplay,
	VideoFrame: VideoFrame,
	ViewportFrame: ViewportFrame,
	LayerCollector: LayerCollector,
	BillboardGui: BillboardGui,
	ScreenGui: ScreenGui,
	GuiMain: GuiMain,
	SurfaceGuiBase: SurfaceGuiBase,
	AdGui: AdGui,
	SurfaceGui: SurfaceGui,
	GuiBase3d: GuiBase3d,
	FloorWire: FloorWire,
	InstanceAdornment: InstanceAdornment,
	SelectionBox: SelectionBox,
	PVAdornment: PVAdornment,
	HandleAdornment: HandleAdornment,
	BoxHandleAdornment: BoxHandleAdornment,
	ConeHandleAdornment: ConeHandleAdornment,
	CylinderHandleAdornment: CylinderHandleAdornment,
	ImageHandleAdornment: ImageHandleAdornment,
	LineHandleAdornment: LineHandleAdornment,
	SphereHandleAdornment: SphereHandleAdornment,
	ParabolaAdornment: ParabolaAdornment,
	SelectionSphere: SelectionSphere,
	PartAdornment: PartAdornment,
	HandlesBase: HandlesBase,
	ArcHandles: ArcHandles,
	Handles: Handles,
	SurfaceSelection: SurfaceSelection,
	SelectionLasso: SelectionLasso,
	SelectionPartLasso: SelectionPartLasso,
	SelectionPointLasso: SelectionPointLasso,
	Path2D: Path2D,
	GuidRegistryService: GuidRegistryService,
	HapticEffect: HapticEffect,
	HeapProfilerService: HeapProfilerService,
	HeatmapService: HeatmapService,
	HiddenSurfaceRemovalAsset: HiddenSurfaceRemovalAsset,
	Highlight: Highlight,
	Hopper: Hopper,
	HttpRbxApiService: HttpRbxApiService,
	HttpRequest: HttpRequest,
	HttpService: HttpService,
	Humanoid: Humanoid,
	HumanoidDescription: HumanoidDescription,
	HumanoidRigDescription: HumanoidRigDescription,
	IKControl: IKControl,
	ILegacyStudioBridge: ILegacyStudioBridge,
	InputAction: InputAction,
	InputBinding: InputBinding,
	InputContext: InputContext,
	InputObject: InputObject,
	InsertService: InsertService,
	JointInstance: JointInstance,
	DynamicRotate: DynamicRotate,
	RotateP: RotateP,
	RotateV: RotateV,
	Glue: Glue,
	ManualSurfaceJointInstance: ManualSurfaceJointInstance,
	ManualGlue: ManualGlue,
	ManualWeld: ManualWeld,
	Motor: Motor,
	Motor6D: Motor6D,
	Rotate: Rotate,
	Snap: Snap,
	VelocityMotor: VelocityMotor,
	Weld: Weld,
	JointsService: JointsService,
	KeyboardService: KeyboardService,
	Keyframe: Keyframe,
	KeyframeMarker: KeyframeMarker,
	Light: Light,
	PointLight: PointLight,
	SpotLight: SpotLight,
	SurfaceLight: SurfaceLight,
	Lighting: Lighting,
	LiveScriptingService: LiveScriptingService,
	LocalizationTable: LocalizationTable,
	LodDataEntity: LodDataEntity,
	LogService: LogService,
	LoginService: LoginService,
	LuaSourceContainer: LuaSourceContainer,
	AuroraScript: AuroraScript,
	BaseScript: BaseScript,
	Script: Script,
	LocalScript: LocalScript,
	ModuleScript: ModuleScript,
	LuaWebService: LuaWebService,
	MLModelDeliveryService: MLModelDeliveryService,
	MarkerCurve: MarkerCurve,
	MarketplaceService: MarketplaceService,
	MaterialService: MaterialService,
	MaterialVariant: MaterialVariant,
	MemoryStoreService: MemoryStoreService,
	Message: Message,
	Hint: Hint,
	Mouse: Mouse,
	PlayerMouse: PlayerMouse,
	PluginMouse: PluginMouse,
	NetworkMarker: NetworkMarker,
	NetworkPeer: NetworkPeer,
	NoCollisionConstraint: NoCollisionConstraint,
	NotificationService: NotificationService,
	OperationGraph: OperationGraph,
	PVInstance: PVInstance,
	BasePart: BasePart,
	CornerWedgePart: CornerWedgePart,
	FormFactorPart: FormFactorPart,
	Part: Part,
	FlagStand: FlagStand,
	Platform: Platform,
	Seat: Seat,
	SpawnLocation: SpawnLocation,
	WedgePart: WedgePart,
	Terrain: Terrain,
	TriangleMeshPart: TriangleMeshPart,
	MeshPart: MeshPart,
	PartOperation: PartOperation,
	IntersectOperation: IntersectOperation,
	NegateOperation: NegateOperation,
	UnionOperation: UnionOperation,
	TrussPart: TrussPart,
	VehicleSeat: VehicleSeat,
	Model: Model,
	Actor: Actor,
	BackpackItem: BackpackItem,
	HopperBin: HopperBin,
	Tool: Tool,
	Flag: Flag,
	Status: Status,
	WorldRoot: WorldRoot,
	Workspace: Workspace,
	WorldModel: WorldModel,
	PackageLink: PackageLink,
	PartOperationAsset: PartOperationAsset,
	ParticleEmitter: ParticleEmitter,
	PathfindingLink: PathfindingLink,
	PathfindingModifier: PathfindingModifier,
	PermissionsService: PermissionsService,
	PhysicsService: PhysicsService,
	Player: Player,
	PlayerHydrationService: PlayerHydrationService,
	Players: Players,
	Plugin: Plugin,
	PluginCapabilities: PluginCapabilities,
	PluginManager: PluginManager,
	PluginToolbar: PluginToolbar,
	PluginToolbarButton: PluginToolbarButton,
	PointsService: PointsService,
	PoseBase: PoseBase,
	NumberPose: NumberPose,
	Pose: Pose,
	PostEffect: PostEffect,
	BloomEffect: BloomEffect,
	BlurEffect: BlurEffect,
	ColorCorrectionEffect: ColorCorrectionEffect,
	ColorGradingEffect: ColorGradingEffect,
	DepthOfFieldEffect: DepthOfFieldEffect,
	SunRaysEffect: SunRaysEffect,
	ProcessInstancePhysicsService: ProcessInstancePhysicsService,
	ProximityPrompt: ProximityPrompt,
	ProximityPromptService: ProximityPromptService,
	RbxAnalyticsService: RbxAnalyticsService,
	ReflectionMetadata: ReflectionMetadata,
	ReflectionMetadataCallbacks: ReflectionMetadataCallbacks,
	ReflectionMetadataClasses: ReflectionMetadataClasses,
	ReflectionMetadataEnums: ReflectionMetadataEnums,
	ReflectionMetadataEvents: ReflectionMetadataEvents,
	ReflectionMetadataFunctions: ReflectionMetadataFunctions,
	ReflectionMetadataItem: ReflectionMetadataItem,
	ReflectionMetadataClass: ReflectionMetadataClass,
	ReflectionMetadataEnum: ReflectionMetadataEnum,
	ReflectionMetadataEnumItem: ReflectionMetadataEnumItem,
	ReflectionMetadataMember: ReflectionMetadataMember,
	ReflectionMetadataProperties: ReflectionMetadataProperties,
	ReflectionMetadataYieldFunctions: ReflectionMetadataYieldFunctions,
	RemoteCursorService: RemoteCursorService,
	RemoteFunction: RemoteFunction,
	RenderingTest: RenderingTest,
	ReplicatedFirst: ReplicatedFirst,
	ReplicatedStorage: ReplicatedStorage,
	RobloxReplicatedStorage: RobloxReplicatedStorage,
	RomarkRbxAnalyticsService: RomarkRbxAnalyticsService,
	RomarkService: RomarkService,
	RotationCurve: RotationCurve,
	SafetyService: SafetyService,
	ScriptDebugger: ScriptDebugger,
	ScriptProfilerService: ScriptProfilerService,
	ScriptService: ScriptService,
	Selection: Selection,
	SelectionHighlightManager: SelectionHighlightManager,
	SensorBase: SensorBase,
	AtmosphereSensor: AtmosphereSensor,
	BuoyancySensor: BuoyancySensor,
	ControllerSensor: ControllerSensor,
	ControllerPartSensor: ControllerPartSensor,
	FluidForceSensor: FluidForceSensor,
	SerializationService: SerializationService,
	ServiceProvider: ServiceProvider,
	DataModel: DataModel,
	GenericSettings: GenericSettings,
	AnalysticsSettings: AnalysticsSettings,
	GlobalSettings: GlobalSettings,
	UserSettings: UserSettings,
	ServiceVisibilityService: ServiceVisibilityService,
	SessionService: SessionService,
	Sky: Sky,
	Smoke: Smoke,
	Sound: Sound,
	SoundEffect: SoundEffect,
	ChorusSoundEffect: ChorusSoundEffect,
	CompressorSoundEffect: CompressorSoundEffect,
	CustomSoundEffect: CustomSoundEffect,
	AssetSoundEffect: AssetSoundEffect,
	ChannelSelectorSoundEffect: ChannelSelectorSoundEffect,
	DistortionSoundEffect: DistortionSoundEffect,
	EchoSoundEffect: EchoSoundEffect,
	EqualizerSoundEffect: EqualizerSoundEffect,
	FlangeSoundEffect: FlangeSoundEffect,
	PitchShiftSoundEffect: PitchShiftSoundEffect,
	ReverbSoundEffect: ReverbSoundEffect,
	TremoloSoundEffect: TremoloSoundEffect,
	SoundGroup: SoundGroup,
	SoundService: SoundService,
	Sparkles: Sparkles,
	SpawnerService: SpawnerService,
	StandalonePluginScripts: StandalonePluginScripts,
	StarterGear: StarterGear,
	StarterPack: StarterPack,
	StarterPlayer: StarterPlayer,
	StarterPlayerScripts: StarterPlayerScripts,
	StarterCharacterScripts: StarterCharacterScripts,
	Stats: Stats,
	StatsItem: StatsItem,
	RunningAverageItemDouble: RunningAverageItemDouble,
	RunningAverageItemInt: RunningAverageItemInt,
	RunningAverageTimeIntervalItem: RunningAverageTimeIntervalItem,
	TotalCountTimeIntervalItem: TotalCountTimeIntervalItem,
	StudioData: StudioData,
	StyleBase: StyleBase,
	StyleRule: StyleRule,
	StyleSheet: StyleSheet,
	StyleDerive: StyleDerive,
	StyleLink: StyleLink,
	SurfaceAppearance: SurfaceAppearance,
	Team: Team,
	TeamCreateData: TeamCreateData,
	TeamCreatePublishService: TeamCreatePublishService,
	Teams: Teams,
	TeleportAsyncResult: TeleportAsyncResult,
	TeleportOptions: TeleportOptions,
	TeleportService: TeleportService,
	TerrainDetail: TerrainDetail,
	TerrainRegion: TerrainRegion,
	TestService: TestService,
	TextBoxService: TextBoxService,
	TextChannel: TextChannel,
	TextChatCommand: TextChatCommand,
	BubbleChatConfiguration: BubbleChatConfiguration,
	ChannelTabsConfiguration: ChannelTabsConfiguration,
	ChatInputBarConfiguration: ChatInputBarConfiguration,
	ChatWindowConfiguration: ChatWindowConfiguration,
	TextChatMessage: TextChatMessage,
	TextChatMessageProperties: TextChatMessageProperties,
	BubbleChatMessageProperties: BubbleChatMessageProperties,
	ChatWindowMessageProperties: ChatWindowMessageProperties,
	TextChatService: TextChatService,
	TextSource: TextSource,
	TimerService: TimerService,
	TouchInputService: TouchInputService,
	TouchTransmitter: TouchTransmitter,
	Trail: Trail,
	TweenBase: TweenBase,
	Tween: Tween,
	TweenService: TweenService,
	UGCAvatarService: UGCAvatarService,
	UIBase: UIBase,
	UIComponent: UIComponent,
	UIConstraint: UIConstraint,
	UIAspectRatioConstraint: UIAspectRatioConstraint,
	UISizeConstraint: UISizeConstraint,
	UITextSizeConstraint: UITextSizeConstraint,
	UICorner: UICorner,
	UIDragDetector: UIDragDetector,
	UIFlexItem: UIFlexItem,
	UIGradient: UIGradient,
	UILayout: UILayout,
	UIGridStyleLayout: UIGridStyleLayout,
	UIGridLayout: UIGridLayout,
	UIListLayout: UIListLayout,
	UIPageLayout: UIPageLayout,
	UITableLayout: UITableLayout,
	UIPadding: UIPadding,
	UIScale: UIScale,
	UIStroke: UIStroke,
	UniqueIdLookupService: UniqueIdLookupService,
	UnvalidatedAssetService: UnvalidatedAssetService,
	UserService: UserService,
	VRService: VRService,
	VRStatusService: VRStatusService,
	ValueBase: ValueBase,
	BinaryStringValue: BinaryStringValue,
	BoolValue: BoolValue,
	BrickColorValue: BrickColorValue,
	CFrameValue: CFrameValue,
	Color3Value: Color3Value,
	DoubleConstrainedValue: DoubleConstrainedValue,
	IntConstrainedValue: IntConstrainedValue,
	IntValue: IntValue,
	NumberValue: NumberValue,
	ObjectValue: ObjectValue,
	RayValue: RayValue,
	StringValue: StringValue,
	Vector3Value: Vector3Value,
	Vector3Curve: Vector3Curve,
	VersionControlService: VersionControlService,
	VideoCaptureService: VideoCaptureService,
	VideoPlayer: VideoPlayer,
	VideoService: VideoService,
	VirtualInputManager: VirtualInputManager,
	VisibilityCheckDispatcher: VisibilityCheckDispatcher,
	VisualizationMode: VisualizationMode,
	VisualizationModeCategory: VisualizationModeCategory,
	VisualizationModeService: VisualizationModeService,
	VoiceChatInternal: VoiceChatInternal,
	VoiceChatService: VoiceChatService,
	WeldConstraint: WeldConstraint,
	Wire: Wire,
	SkateboardPlatform: SkateboardPlatform,
	WireframeHandleAdornment: WireframeHandleAdornment,
}

--- Set of supported Instance classes.
local supported_table: { [string]: boolean } = {}

supported_table.Instance = true
supported_table.AccessoryDescription = true
supported_table.Accoutrement = true
supported_table.Accessory = true
supported_table.Hat = true
supported_table.ActivityHistoryEventService = true
supported_table.AdPortal = true
supported_table.AdService = true
supported_table.AdvancedDragger = true
supported_table.Animation = true
supported_table.AnimationClip = true
supported_table.CurveAnimation = true
supported_table.KeyframeSequence = true
supported_table.AnimationController = true
supported_table.AnimationFromVideoCreatorService = true
supported_table.AnimationRigData = true
supported_table.AnimationTrack = true
supported_table.Animator = true
supported_table.Annotation = true
supported_table.WorkspaceAnnotation = true
supported_table.AnnotationsService = true
supported_table.AssetService = true
supported_table.Atmosphere = true
supported_table.Attachment = true
supported_table.Bone = true
supported_table.AudioAnalyzer = true
supported_table.AudioChannelMixer = true
supported_table.AudioChannelSplitter = true
supported_table.AudioChorus = true
supported_table.AudioCompressor = true
supported_table.AudioDeviceInput = true
supported_table.AudioDeviceOutput = true
supported_table.AudioDistortion = true
supported_table.AudioEcho = true
supported_table.AudioEmitter = true
supported_table.AudioEqualizer = true
supported_table.AudioFader = true
supported_table.AudioFilter = true
supported_table.AudioFlanger = true
supported_table.AudioLimiter = true
supported_table.AudioListener = true
supported_table.AudioPitchShifter = true
supported_table.AudioPlayer = true
supported_table.AudioReverb = true
supported_table.AudioTextToSpeech = true
supported_table.AuroraScriptService = true
supported_table.AuroraService = true
supported_table.AvatarChatService = true
supported_table.AvatarCreationService = true
supported_table.Backpack = true
supported_table.BadgeService = true
supported_table.BasePlayerGui = true
supported_table.PlayerGui = true
supported_table.StarterGui = true
supported_table.BaseRemoteEvent = true
supported_table.RemoteEvent = true
supported_table.UnreliableRemoteEvent = true
supported_table.BaseWrap = true
supported_table.WrapDeformer = true
supported_table.WrapLayer = true
supported_table.WrapTarget = true
supported_table.Beam = true
supported_table.BindableEvent = true
supported_table.BindableFunction = true
supported_table.BodyMover = true
supported_table.BodyAngularVelocity = true
supported_table.BodyForce = true
supported_table.BodyGyro = true
supported_table.BodyPosition = true
supported_table.BodyThrust = true
supported_table.BodyVelocity = true
supported_table.RocketPropulsion = true
supported_table.BodyPartDescription = true
supported_table.CaptureService = true
supported_table.ChangeHistoryService = true
supported_table.CharacterAppearance = true
supported_table.BodyColors = true
supported_table.CharacterMesh = true
supported_table.Clothing = true
supported_table.Pants = true
supported_table.Shirt = true
supported_table.ShirtGraphic = true
supported_table.Skin = true
supported_table.ClickDetector = true
supported_table.DragDetector = true
supported_table.Clouds = true
supported_table.Collaborator = true
supported_table.CollaboratorsService = true
supported_table.CollectionService = true
supported_table.CommerceService = true
supported_table.Configuration = true
supported_table.ConfigureServerService = true
supported_table.Constraint = true
supported_table.AlignOrientation = true
supported_table.AlignPosition = true
supported_table.AngularVelocity = true
supported_table.AnimationConstraint = true
supported_table.BallSocketConstraint = true
supported_table.HingeConstraint = true
supported_table.LineForce = true
supported_table.LinearVelocity = true
supported_table.PlaneConstraint = true
supported_table.Plane = true
supported_table.RigidConstraint = true
supported_table.RodConstraint = true
supported_table.RopeConstraint = true
supported_table.SlidingBallConstraint = true
supported_table.CylindricalConstraint = true
supported_table.PrismaticConstraint = true
supported_table.SpringConstraint = true
supported_table.Torque = true
supported_table.TorsionSpringConstraint = true
supported_table.UniversalConstraint = true
supported_table.VectorForce = true
supported_table.ContextActionService = true
supported_table.Controller = true
supported_table.HumanoidController = true
supported_table.SkateboardController = true
supported_table.VehicleController = true
supported_table.ControllerBase = true
supported_table.AirController = true
supported_table.ClimbController = true
supported_table.GroundController = true
supported_table.SwimController = true
supported_table.ControllerManager = true
supported_table.CookiesService = true
supported_table.CoreScriptDebuggingManagerHelper = true
supported_table.CreatorStoreService = true
supported_table.CustomEvent = true
supported_table.CustomEventReceiver = true
supported_table.DataModelMesh = true
supported_table.BevelMesh = true
supported_table.BlockMesh = true
supported_table.CylinderMesh = true
supported_table.FileMesh = true
supported_table.SpecialMesh = true
supported_table.DataModelSession = true
supported_table.Debris = true
supported_table.DebuggerBreakpoint = true
supported_table.DebuggerWatch = true
supported_table.Dialog = true
supported_table.DialogChoice = true
supported_table.Dragger = true
supported_table.EditableService = true
supported_table.EulerRotationCurve = true
supported_table.EventIngestService = true
supported_table.ExperienceAuthService = true
supported_table.Explosion = true
supported_table.FaceControls = true
supported_table.FaceInstance = true
supported_table.Decal = true
supported_table.Texture = true
supported_table.FacialAnimationStreamingServiceV2 = true
supported_table.Feature = true
supported_table.Hole = true
supported_table.MotorFeature = true
supported_table.FeatureRestrictionManager = true
supported_table.Fire = true
supported_table.FlagStandService = true
supported_table.FloatCurve = true
supported_table.FlyweightService = true
supported_table.CSGDictionaryService = true
supported_table.NonReplicatedCSGDictionaryService = true
supported_table.Folder = true
supported_table.ForceField = true
supported_table.FriendService = true
supported_table.FunctionalTest = true
supported_table.GamePassService = true
supported_table.GenerationService = true
supported_table.GenericChallengeService = true
supported_table.Geometry = true
supported_table.GeometryService = true
supported_table.GoogleAnalyticsConfiguration = true
supported_table.GuiBase = true
supported_table.GuiBase2d = true
supported_table.GuiObject = true
supported_table.CanvasGroup = true
supported_table.Frame = true
supported_table.GuiButton = true
supported_table.ImageButton = true
supported_table.TextButton = true
supported_table.GuiLabel = true
supported_table.ImageLabel = true
supported_table.TextLabel = true
supported_table.ScrollingFrame = true
supported_table.TextBox = true
supported_table.VideoDisplay = true
supported_table.VideoFrame = true
supported_table.ViewportFrame = true
supported_table.LayerCollector = true
supported_table.BillboardGui = true
supported_table.ScreenGui = true
supported_table.GuiMain = true
supported_table.SurfaceGuiBase = true
supported_table.AdGui = true
supported_table.SurfaceGui = true
supported_table.GuiBase3d = true
supported_table.FloorWire = true
supported_table.InstanceAdornment = true
supported_table.SelectionBox = true
supported_table.PVAdornment = true
supported_table.HandleAdornment = true
supported_table.BoxHandleAdornment = true
supported_table.ConeHandleAdornment = true
supported_table.CylinderHandleAdornment = true
supported_table.ImageHandleAdornment = true
supported_table.LineHandleAdornment = true
supported_table.SphereHandleAdornment = true
supported_table.ParabolaAdornment = true
supported_table.SelectionSphere = true
supported_table.PartAdornment = true
supported_table.HandlesBase = true
supported_table.ArcHandles = true
supported_table.Handles = true
supported_table.SurfaceSelection = true
supported_table.SelectionLasso = true
supported_table.SelectionPartLasso = true
supported_table.SelectionPointLasso = true
supported_table.Path2D = true
supported_table.GuidRegistryService = true
supported_table.HapticEffect = true
supported_table.HeapProfilerService = true
supported_table.HeatmapService = true
supported_table.HiddenSurfaceRemovalAsset = true
supported_table.Highlight = true
supported_table.Hopper = true
supported_table.HttpRbxApiService = true
supported_table.HttpRequest = true
supported_table.HttpService = true
supported_table.Humanoid = true
supported_table.HumanoidDescription = true
supported_table.HumanoidRigDescription = true
supported_table.IKControl = true
supported_table.ILegacyStudioBridge = true
supported_table.InputAction = true
supported_table.InputBinding = true
supported_table.InputContext = true
supported_table.InputObject = true
supported_table.InsertService = true
supported_table.JointInstance = true
supported_table.DynamicRotate = true
supported_table.RotateP = true
supported_table.RotateV = true
supported_table.Glue = true
supported_table.ManualSurfaceJointInstance = true
supported_table.ManualGlue = true
supported_table.ManualWeld = true
supported_table.Motor = true
supported_table.Motor6D = true
supported_table.Rotate = true
supported_table.Snap = true
supported_table.VelocityMotor = true
supported_table.Weld = true
supported_table.JointsService = true
supported_table.KeyboardService = true
supported_table.Keyframe = true
supported_table.KeyframeMarker = true
supported_table.Light = true
supported_table.PointLight = true
supported_table.SpotLight = true
supported_table.SurfaceLight = true
supported_table.Lighting = true
supported_table.LiveScriptingService = true
supported_table.LocalizationTable = true
supported_table.LodDataEntity = true
supported_table.LogService = true
supported_table.LoginService = true
supported_table.LuaSourceContainer = true
supported_table.AuroraScript = true
supported_table.BaseScript = true
supported_table.Script = true
supported_table.LocalScript = true
supported_table.ModuleScript = true
supported_table.LuaWebService = true
supported_table.MLModelDeliveryService = true
supported_table.MarkerCurve = true
supported_table.MarketplaceService = true
supported_table.MaterialService = true
supported_table.MaterialVariant = true
supported_table.MemoryStoreService = true
supported_table.Message = true
supported_table.Hint = true
supported_table.Mouse = true
supported_table.PlayerMouse = true
supported_table.PluginMouse = true
supported_table.NetworkMarker = true
supported_table.NetworkPeer = true
supported_table.NoCollisionConstraint = true
supported_table.NotificationService = true
supported_table.OperationGraph = true
supported_table.PVInstance = true
supported_table.BasePart = true
supported_table.CornerWedgePart = true
supported_table.FormFactorPart = true
supported_table.Part = true
supported_table.FlagStand = true
supported_table.Platform = true
supported_table.Seat = true
supported_table.SpawnLocation = true
supported_table.WedgePart = true
supported_table.Terrain = true
supported_table.TriangleMeshPart = true
supported_table.MeshPart = true
supported_table.PartOperation = true
supported_table.IntersectOperation = true
supported_table.NegateOperation = true
supported_table.UnionOperation = true
supported_table.TrussPart = true
supported_table.VehicleSeat = true
supported_table.Model = true
supported_table.Actor = true
supported_table.BackpackItem = true
supported_table.HopperBin = true
supported_table.Tool = true
supported_table.Flag = true
supported_table.Status = true
supported_table.WorldRoot = true
supported_table.Workspace = true
supported_table.WorldModel = true
supported_table.PackageLink = true
supported_table.PartOperationAsset = true
supported_table.ParticleEmitter = true
supported_table.PathfindingLink = true
supported_table.PathfindingModifier = true
supported_table.PermissionsService = true
supported_table.PhysicsService = true
supported_table.Player = true
supported_table.PlayerHydrationService = true
supported_table.Players = true
supported_table.Plugin = true
supported_table.PluginCapabilities = true
supported_table.PluginManager = true
supported_table.PluginToolbar = true
supported_table.PluginToolbarButton = true
supported_table.PointsService = true
supported_table.PoseBase = true
supported_table.NumberPose = true
supported_table.Pose = true
supported_table.PostEffect = true
supported_table.BloomEffect = true
supported_table.BlurEffect = true
supported_table.ColorCorrectionEffect = true
supported_table.ColorGradingEffect = true
supported_table.DepthOfFieldEffect = true
supported_table.SunRaysEffect = true
supported_table.ProcessInstancePhysicsService = true
supported_table.ProximityPrompt = true
supported_table.ProximityPromptService = true
supported_table.RbxAnalyticsService = true
supported_table.ReflectionMetadata = true
supported_table.ReflectionMetadataCallbacks = true
supported_table.ReflectionMetadataClasses = true
supported_table.ReflectionMetadataEnums = true
supported_table.ReflectionMetadataEvents = true
supported_table.ReflectionMetadataFunctions = true
supported_table.ReflectionMetadataItem = true
supported_table.ReflectionMetadataClass = true
supported_table.ReflectionMetadataEnum = true
supported_table.ReflectionMetadataEnumItem = true
supported_table.ReflectionMetadataMember = true
supported_table.ReflectionMetadataProperties = true
supported_table.ReflectionMetadataYieldFunctions = true
supported_table.RemoteCursorService = true
supported_table.RemoteFunction = true
supported_table.RenderingTest = true
supported_table.ReplicatedFirst = true
supported_table.ReplicatedStorage = true
supported_table.RobloxReplicatedStorage = true
supported_table.RomarkRbxAnalyticsService = true
supported_table.RomarkService = true
supported_table.RotationCurve = true
supported_table.SafetyService = true
supported_table.ScriptDebugger = true
supported_table.ScriptProfilerService = true
supported_table.ScriptService = true
supported_table.Selection = true
supported_table.SelectionHighlightManager = true
supported_table.SensorBase = true
supported_table.AtmosphereSensor = true
supported_table.BuoyancySensor = true
supported_table.ControllerSensor = true
supported_table.ControllerPartSensor = true
supported_table.FluidForceSensor = true
supported_table.SerializationService = true
supported_table.ServiceProvider = true
supported_table.DataModel = true
supported_table.GenericSettings = true
supported_table.AnalysticsSettings = true
supported_table.GlobalSettings = true
supported_table.UserSettings = true
supported_table.ServiceVisibilityService = true
supported_table.SessionService = true
supported_table.Sky = true
supported_table.Smoke = true
supported_table.Sound = true
supported_table.SoundEffect = true
supported_table.ChorusSoundEffect = true
supported_table.CompressorSoundEffect = true
supported_table.CustomSoundEffect = true
supported_table.AssetSoundEffect = true
supported_table.ChannelSelectorSoundEffect = true
supported_table.DistortionSoundEffect = true
supported_table.EchoSoundEffect = true
supported_table.EqualizerSoundEffect = true
supported_table.FlangeSoundEffect = true
supported_table.PitchShiftSoundEffect = true
supported_table.ReverbSoundEffect = true
supported_table.TremoloSoundEffect = true
supported_table.SoundGroup = true
supported_table.SoundService = true
supported_table.Sparkles = true
supported_table.SpawnerService = true
supported_table.StandalonePluginScripts = true
supported_table.StarterGear = true
supported_table.StarterPack = true
supported_table.StarterPlayer = true
supported_table.StarterPlayerScripts = true
supported_table.StarterCharacterScripts = true
supported_table.Stats = true
supported_table.StatsItem = true
supported_table.RunningAverageItemDouble = true
supported_table.RunningAverageItemInt = true
supported_table.RunningAverageTimeIntervalItem = true
supported_table.TotalCountTimeIntervalItem = true
supported_table.StudioData = true
supported_table.StyleBase = true
supported_table.StyleRule = true
supported_table.StyleSheet = true
supported_table.StyleDerive = true
supported_table.StyleLink = true
supported_table.SurfaceAppearance = true
supported_table.Team = true
supported_table.TeamCreateData = true
supported_table.TeamCreatePublishService = true
supported_table.Teams = true
supported_table.TeleportAsyncResult = true
supported_table.TeleportOptions = true
supported_table.TeleportService = true
supported_table.TerrainDetail = true
supported_table.TerrainRegion = true
supported_table.TestService = true
supported_table.TextBoxService = true
supported_table.TextChannel = true
supported_table.TextChatCommand = true
supported_table.BubbleChatConfiguration = true
supported_table.ChannelTabsConfiguration = true
supported_table.ChatInputBarConfiguration = true
supported_table.ChatWindowConfiguration = true
supported_table.TextChatMessage = true
supported_table.TextChatMessageProperties = true
supported_table.BubbleChatMessageProperties = true
supported_table.ChatWindowMessageProperties = true
supported_table.TextChatService = true
supported_table.TextSource = true
supported_table.TimerService = true
supported_table.TouchInputService = true
supported_table.TouchTransmitter = true
supported_table.Trail = true
supported_table.TweenBase = true
supported_table.Tween = true
supported_table.TweenService = true
supported_table.UGCAvatarService = true
supported_table.UIBase = true
supported_table.UIComponent = true
supported_table.UIConstraint = true
supported_table.UIAspectRatioConstraint = true
supported_table.UISizeConstraint = true
supported_table.UITextSizeConstraint = true
supported_table.UICorner = true
supported_table.UIDragDetector = true
supported_table.UIFlexItem = true
supported_table.UIGradient = true
supported_table.UILayout = true
supported_table.UIGridStyleLayout = true
supported_table.UIGridLayout = true
supported_table.UIListLayout = true
supported_table.UIPageLayout = true
supported_table.UITableLayout = true
supported_table.UIPadding = true
supported_table.UIScale = true
supported_table.UIStroke = true
supported_table.UniqueIdLookupService = true
supported_table.UnvalidatedAssetService = true
supported_table.UserService = true
supported_table.VRService = true
supported_table.VRStatusService = true
supported_table.ValueBase = true
supported_table.BinaryStringValue = true
supported_table.BoolValue = true
supported_table.BrickColorValue = true
supported_table.CFrameValue = true
supported_table.Color3Value = true
supported_table.DoubleConstrainedValue = true
supported_table.IntConstrainedValue = true
supported_table.IntValue = true
supported_table.NumberValue = true
supported_table.ObjectValue = true
supported_table.RayValue = true
supported_table.StringValue = true
supported_table.Vector3Value = true
supported_table.Vector3Curve = true
supported_table.VersionControlService = true
supported_table.VideoCaptureService = true
supported_table.VideoPlayer = true
supported_table.VideoService = true
supported_table.VirtualInputManager = true
supported_table.VisibilityCheckDispatcher = true
supported_table.VisualizationMode = true
supported_table.VisualizationModeCategory = true
supported_table.VisualizationModeService = true
supported_table.VoiceChatInternal = true
supported_table.VoiceChatService = true
supported_table.WeldConstraint = true
supported_table.Wire = true
supported_table.SkateboardPlatform = true
supported_table.WireframeHandleAdornment = true

return supported_table
