name: Run Tests

permissions:
  contents: read

defaults:
  run:
    shell: bash

on:
  push:
    branches:
      - main
    paths:
      - .github/workflows/tests.yml
      - lune/**
      - src/**
      - tests/**
      - pesde.toml

  pull_request:
  workflow_dispatch:
  merge_group:

jobs:
  Test:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          # only checkout files which are needed for running tests
          sparse-checkout: |
            rokit.toml
            .luaurc
            lune/
            src/
            tests/
          sparse-checkout-cone-mode: false

      - name: Setup Rokit
        uses: CompeyDev/setup-rokit@v0.1.2

      - name: Run Test Script
        run: lune run lune/tests.luau
